name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: # enabled

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:

          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics

          template: classic
          repositories_affiliations: ''
          commits_authoring: ptforness
          config_timezone: Pacific/Auckland # NZT

          plugin_lines: yes
          plugin_traffic: yes

          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories, user

          plugin_discussions: yes

          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_sections: most-used, recently-used
          plugin_languages_categories: programming
          plugin_languages_recent_categories: programming, markup
          plugin_languages_ignored: NWScript
          plugin_languages_indepth: yes

          plugin_gists: yes

          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0 # disable

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_timestamps: yes

          plugin_code: yes

          plugin_reactions: yes
          plugin_reactions_details: count
          plugin_reactions_limit: 200
